response_code = {
    200 : "SUCCESS",
    201 : "CREATED",
    300 : "VALIDATION_ERROR",
    401 : "USERNAME_ALREADY_EXISTS",
    402 : "EMAIL_ID_ALREADY_EXISTS",
    403 : "PASSWORD_DIDNT_MATCHED",
    404 : "PROVIDE_VALID_EMAIL",  
    405 : "INVALID_DATA",
    406 : "PLEASE_ENTER_ALPHA_NUMERIC_PASSWORD",
}